'use client'
import Link from 'next/link'
import { useState } from 'react'
import { useApi } from '@/lib/use-api'
import { RequireAuth } from '@/features/auth/require-auth'
import { Input } from '@/components/ui/input'
import { Button } from '@/components/ui/button'
export type AdminAccount={id:string;fullName:string;email:string|null;phone:string|null;emailVerified:boolean;phoneVerified:boolean;roles:string[];status:string;createdAt:string;lastLoginAt:string|null;lockedAt:string|null;lockedUntil:string|null;lockReason:string|null}
export function AdminAccounts(){return <RequireAuth roles={['ADMIN']}><Loaded/></RequireAuth>}
function Loaded(){const [path,setPath]=useState('/admin/accounts');const r=useApi<AdminAccount[]>(path)
 function search(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),p=new URLSearchParams();for(const key of ['q','status','role']){const v=String(f.get(key)||'');if(v)p.set(key,v)}setPath(`/admin/accounts?${p}`)}
 return <div className="mx-auto max-w-6xl px-5 py-10"><p className="text-sm font-bold text-emerald-700">QUẢN TRỊ SPORTHUB</p><h1 className="mt-3 text-3xl font-black">Tài khoản</h1><AdminNav active="accounts"/><form onSubmit={search} className="mt-6 grid gap-4 rounded-2xl bg-slate-50 p-5 md:grid-cols-4"><label className="grid gap-2 text-sm">Tên hoặc liên hệ<Input name="q" placeholder="Họ tên, email, số điện thoại"/></label><label className="grid gap-2 text-sm">Trạng thái<select name="status" className="h-10 rounded-lg border bg-white px-3"><option value="">Tất cả</option>{['ACTIVE','LOCKED','PENDING_VERIFICATION','SUSPENDED','DEACTIVATED'].map(s=><option key={s}>{s}</option>)}</select></label><label className="grid gap-2 text-sm">Vai trò<select name="role" className="h-10 rounded-lg border bg-white px-3"><option value="">Tất cả</option>{['CUSTOMER','OWNER','STAFF','ADMIN'].map(s=><option key={s}>{s}</option>)}</select></label><Button type="submit" className="mt-auto bg-emerald-600 text-white">Tra cứu</Button></form>{r.loading&&<p role="status" className="mt-6">Đang tải tài khoản…</p>}{r.error&&<p role="alert" className="mt-6 text-red-700">{r.error}<button onClick={r.reload} className="ml-4 underline">Thử lại</button></p>}{r.data?.length===0&&<p className="mt-6 rounded-xl border p-6 text-slate-500">Không tìm thấy tài khoản phù hợp.</p>}<div className="mt-6 divide-y rounded-2xl border">{r.data?.map(u=><Link className="flex flex-wrap items-center justify-between gap-4 p-5 hover:bg-emerald-50" href={`/admin/accounts/${u.id}`} key={u.id}><div><h2 className="font-bold">{u.fullName}</h2><p className="mt-2 text-sm text-slate-500">{u.email||u.phone}</p></div><div className="text-right"><span className="text-sm font-semibold text-emerald-700">{u.status}</span><p className="mt-2 text-xs text-slate-500">{u.roles.join(' · ')}</p></div></Link>)}</div><p className="mt-4 text-xs text-slate-500">Tối đa 100 kết quả gần nhất. Dùng bộ lọc để tìm tài khoản cần kiểm tra.</p></div>
}
export function AdminNav({active}:{active:string}){return <nav aria-label="Quản trị nền tảng" className="mt-6 flex gap-2 overflow-x-auto border-b pb-4">{[['accounts','Tài khoản'],['owner-applications','Đăng ký Owner'],['facilities','Cơ sở'],['bookings','Booking'],['payments','Giao dịch'],['reports','Báo cáo']].map(([key,label])=><Link key={key} href={`/admin/${key}`} className={`whitespace-nowrap rounded-full px-4 py-2 text-sm ${active===key?'bg-emerald-600 text-white':'bg-slate-100 text-slate-600'}`}>{label}</Link>)}</nav>}
