'use client'
import Link from 'next/link'
import { useState } from 'react'
import { useApi } from '@/lib/use-api'
import { RequireAuth } from '@/features/auth/require-auth'
import { Input } from '@/components/ui/input'
import { Button } from '@/components/ui/button'
import { type Booking,type BookingDetail,statusLabels } from '@/features/booking/types'
import { money } from '@/features/schedule/types'
import { AdminNav } from './account-list'
export function BookingMonitor(){return <RequireAuth roles={['ADMIN']}><Loaded/></RequireAuth>}
function Loaded(){const [path,setPath]=useState('/admin/bookings');const r=useApi<Booking[]>(path)
 function search(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),p=new URLSearchParams();for(const key of ['id','facilityId','status']){const v=String(f.get(key)||'');if(v)p.set(key,v)}setPath(`/admin/bookings?${p}`)}
 return <div className="mx-auto max-w-6xl px-5 py-10"><h1 className="text-3xl font-black">Giám sát booking</h1><AdminNav active="bookings"/><form onSubmit={search} className="mt-6 grid gap-4 rounded-2xl bg-slate-50 p-5 md:grid-cols-4"><label className="grid gap-2 text-sm">Mã booking<Input name="id" placeholder="UUID booking"/></label><label className="grid gap-2 text-sm">Mã cơ sở<Input name="facilityId" placeholder="UUID cơ sở"/></label><label className="grid gap-2 text-sm">Trạng thái<select name="status" className="h-10 rounded-lg border bg-white px-3"><option value="">Tất cả</option>{['PENDING','CONFIRMED','CHECKED_IN','COMPLETED','CANCELLED','EXPIRED'].map(s=><option value={s} key={s}>{statusLabels[s]}</option>)}</select></label><Button type="submit" className="mt-auto bg-emerald-600 text-white">Tra cứu</Button></form>{r.loading&&<p role="status" className="mt-6">Đang tải booking…</p>}{r.error&&<p role="alert" className="mt-6 text-red-700">{r.error}<button className="ml-4 underline" onClick={r.reload}>Thử lại</button></p>}{r.data?.length===0&&<p className="mt-6 rounded-xl border p-6 text-slate-500">Không có booking phù hợp.</p>}<div className="mt-6 divide-y rounded-2xl border">{r.data?.map(b=><Link key={b.id} href={`/admin/bookings/${b.id}`} className="flex flex-wrap justify-between gap-4 p-5 hover:bg-emerald-50"><div><p className="font-bold">{b.id.slice(0,8).toUpperCase()} · {statusLabels[b.status]}</p><p className="mt-2 text-sm text-slate-500">{new Date(b.startsAt).toLocaleString('vi-VN',{timeZone:b.priceSnapshot.timezone})}</p><p className="mt-2 text-xs text-slate-400">Cơ sở {b.facilityId}</p></div><strong className="text-emerald-700">{money(b.amount,b.currency)}</strong></Link>)}</div><Link href="/admin/bookings/reconciliation" className="mt-6 inline-block text-sm text-emerald-700 underline">Mở danh sách cần đối soát</Link></div>
}
export function AdminBookingDetail({id}:{id:string}){return <RequireAuth roles={['ADMIN']}><Detail id={id}/></RequireAuth>}
function Detail({id}:{id:string}){const r=useApi<BookingDetail>(`/admin/bookings/${id}`);if(r.loading)return <p role="status" className="p-8">Đang tải lịch sử booking…</p>;if(!r.data)return <p className="p-8 text-red-700" role="alert">{r.error}<button className="ml-4 underline" onClick={r.reload}>Thử lại</button></p>;const b=r.data.booking
 return <div className="mx-auto max-w-4xl px-5 py-10"><Link href="/admin/bookings" className="text-sm text-slate-500">Giám sát booking / {id.slice(0,8).toUpperCase()}</Link><h1 className="mt-6 text-3xl font-black">{statusLabels[b.status]}</h1><section className="mt-6 space-y-3 rounded-2xl border p-6"><p className="font-bold text-emerald-700">Giá gốc: {money(b.amount,b.currency)}</p><p>{new Date(b.startsAt).toLocaleString('vi-VN',{timeZone:b.priceSnapshot.timezone})} → {new Date(b.endsAt).toLocaleTimeString('vi-VN',{timeZone:b.priceSnapshot.timezone})}</p><p className="break-all text-sm text-slate-500">Cơ sở {b.facilityId} · Sân {b.courtId}</p><p className="break-all text-sm text-slate-500">Holder hiện tại: {b.currentHolderId}</p>{b.paymentId&&<Link href={`/admin/payments/${b.paymentId}`} className="block text-sm text-emerald-700 underline">Giao dịch thanh toán gốc</Link>}<details><summary className="text-sm">Chi tiết giá tại lúc đặt</summary><pre className="mt-4 overflow-x-auto rounded-lg bg-slate-50 p-4 text-xs">{JSON.stringify(b.priceSnapshot,null,2)}</pre></details></section><h2 className="mt-8 text-xl font-bold">Lịch sử trạng thái và chuyển quyền</h2><ol className="mt-5 space-y-4 border-l-2 border-emerald-100 pl-5">{r.data.history.map(h=><li key={h.id}><p className="font-semibold">{statusLabels[h.action]||h.action}</p><p className="mt-2 text-xs text-slate-500">{new Date(h.createdAt).toLocaleString('vi-VN')}</p><details className="mt-2 text-sm"><summary>Thông tin sự kiện</summary><pre className="mt-3 overflow-x-auto bg-slate-50 p-3 text-xs">{JSON.stringify(h.details,null,2)}</pre></details></li>)}</ol></div>
}
export function BookingReconciliation(){return <RequireAuth roles={['ADMIN']}><Reconciliation/></RequireAuth>}
function Reconciliation(){const r=useApi<{id:string;booking_id:string;payment_id:string;reason:string;state:string;created_at:string}[]>('/admin/bookings/reconciliation');return <div className="mx-auto max-w-5xl px-5 py-10"><Link href="/admin/bookings" className="text-sm text-slate-500">Giám sát booking</Link><h1 className="mt-5 text-3xl font-black">Thanh toán cần đối soát</h1><p className="mt-3 text-slate-500">Các kết quả không đủ điều kiện xác nhận được giữ lại để kiểm tra. Chính sách hoàn tiền chưa được chốt.</p>{r.loading&&<p className="mt-6" role="status">Đang tải đối soát…</p>}{r.error&&<p className="mt-6 text-red-700" role="alert">{r.error}</p>}{r.data?.length===0&&<p className="mt-6 rounded-xl border p-6 text-slate-500">Chưa có trường hợp cần đối soát.</p>}<div className="mt-6 space-y-4">{r.data?.map(x=><article key={x.id} className="rounded-xl border p-5"><p className="font-semibold text-amber-800">{x.reason} · {x.state}</p><div className="mt-3 flex gap-5 text-sm text-emerald-700"><Link href={`/admin/bookings/${x.booking_id}`}>Xem booking</Link><Link href={`/admin/payments/${x.payment_id}`}>Xem giao dịch</Link></div><p className="mt-3 text-xs text-slate-500">{new Date(x.created_at).toLocaleString('vi-VN')}</p></article>)}</div></div>}
