'use client'
import Link from 'next/link'
import { useState } from 'react'
import { api } from '@/lib/api'
import { useApi } from '@/lib/use-api'
import { RequireAuth } from '@/features/auth/require-auth'
import { Input } from '@/components/ui/input'
import { Button } from '@/components/ui/button'
import { type Facility,type Court,type Media } from '@/features/facility/types'
import { type FacilityReview,reviewLabels } from '@/features/facility/review-page'
import { type ReviewDocument } from '@/features/facility/document-page'
import { AdminNav } from './account-list'
export function AdminFacilities(){return <RequireAuth roles={['ADMIN']}><List/></RequireAuth>}
function List(){const [query,setQuery]=useState('status=PENDING_APPROVAL');const r=useApi<Facility[]>(`/admin/facilities?${query}`)
 return <div className="mx-auto max-w-6xl px-5 py-10"><h1 className="text-3xl font-black">Kiểm duyệt cơ sở</h1><AdminNav active="facilities"/><form className="mt-6 flex flex-wrap items-end gap-4 rounded-2xl bg-slate-50 p-5" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget),p=new URLSearchParams();for(const key of ['q','status']){const v=String(f.get(key)||'');if(v)p.set(key,v)}setQuery(p.toString())}}><label className="grid gap-2 text-sm">Tên hoặc địa chỉ<Input name="q" placeholder="Tên, liên hệ, địa chỉ"/></label><label className="grid gap-2 text-sm">Trạng thái<select name="status" defaultValue="PENDING_APPROVAL" className="h-10 rounded-lg border bg-white px-3"><option value="">Tất cả</option>{['DRAFT','PENDING_APPROVAL','ACTIVE','REJECTED','SUSPENDED'].map(state=><option key={state} value={state}>{reviewLabels[state]}</option>)}</select></label><Button type="submit" className="bg-emerald-600 text-white">Tra cứu</Button></form>{r.loading&&<p role="status" className="mt-6">Đang tải hồ sơ cơ sở…</p>}{r.error&&<p role="alert" className="mt-6 text-red-700">{r.error}<button className="ml-4 underline" onClick={r.reload}>Thử lại</button></p>}{r.data?.length===0&&<p className="mt-6 rounded-xl border p-6 text-slate-500">Không có cơ sở phù hợp.</p>}<div className="mt-6 divide-y rounded-2xl border">{r.data?.map(f=><Link href={`/admin/facilities/${f.id}`} key={f.id} className="flex flex-wrap justify-between gap-4 p-6 hover:bg-emerald-50"><div><h2 className="font-bold">{f.name}</h2><p className="mt-2 text-sm text-slate-500">{f.addressLine}, {f.district}, {f.province}</p></div><span className="text-sm font-semibold text-emerald-700">{reviewLabels[f.status]||f.status}</span></Link>)}</div></div>
}
type ReviewDetail={facility:Facility;courts:Court[];reviews:FacilityReview[];audit:{id:string;action:string;occurred_at:string;details:string|null}[];possibleDuplicates:Facility[]}
export function AdminFacilityReview({id}:{id:string}){return <RequireAuth roles={['ADMIN']}><Detail id={id}/></RequireAuth>}
function Detail({id}:{id:string}){const r=useApi<ReviewDetail>(`/admin/facilities/${id}`),docs=useApi<ReviewDocument[]>(`/admin/facilities/${id}/documents`),images=useApi<Media[]>(`/admin/facilities/${id}/images`);const [tab,setTab]=useState('profile');const [action,setAction]=useState<string|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('')
 async function decide(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!action||busy)return;const f=new FormData(e.currentTarget);setBusy(true);setError('');try{await api(`/admin/facilities/${id}/decision`,{method:'POST',body:JSON.stringify({action,reason:f.get('reason')})});setAction(null);r.reload()}catch(err){setError(err instanceof Error?err.message:'Không thể xử lý hồ sơ.')}finally{setBusy(false)}}
 if(r.loading)return <p role="status" className="p-8">Đang tải hồ sơ thẩm định…</p>;if(!r.data)return <p role="alert" className="p-8 text-red-700">{r.error}<button className="ml-3 underline" onClick={r.reload}>Thử lại</button></p>;const f=r.data.facility
 return <div className="mx-auto max-w-5xl px-5 py-10"><Link href="/admin/facilities" className="text-sm text-slate-500">Kiểm duyệt cơ sở</Link><h1 className="mt-5 text-3xl font-black">{f.name}</h1><p className="mt-3 font-semibold text-emerald-700">{reviewLabels[f.status]||f.status}</p>{r.data.possibleDuplicates.length>0&&<section className="mt-5 rounded-xl bg-amber-50 p-5"><h2 className="font-bold text-amber-900">Có địa chỉ trùng với hồ sơ khác</h2>{r.data.possibleDuplicates.map(other=><Link key={other.id} href={`/admin/facilities/${other.id}`} className="mt-3 block text-sm underline">{other.name} · {reviewLabels[other.status]||other.status}</Link>)}</section>}
 <div role="tablist" aria-label="Hồ sơ thẩm định cơ sở" className="mt-6 flex gap-3 border-b pb-4">{[['profile','Thông tin và sân'],['documents','Tài liệu và hình ảnh'],['history','Lịch sử kiểm duyệt']].map(([value,label])=><button role="tab" aria-selected={tab===value} onClick={()=>setTab(value)} key={value} className={`rounded-full px-4 py-2 text-sm ${tab===value?'bg-emerald-600 text-white':'bg-slate-100'}`}>{label}</button>)}</div>
 {tab==='profile'&&<section className="mt-6 space-y-4 rounded-2xl border p-6"><p>{f.addressLine}, {f.ward}, {f.district}, {f.province}</p><p className="text-sm text-slate-500">Liên hệ: {f.phone} · {f.timezone}</p><p className="text-sm">{f.description}</p><p className="text-sm">Tiện ích: {f.amenities.join(', ')||'Chưa khai báo'}</p><Link href={`/admin/accounts/${f.ownerId}`} className="block text-sm text-emerald-700 underline">Xem tài khoản Owner</Link><h2 className="pt-4 text-xl font-bold">{r.data.courts.length} sân</h2>{r.data.courts.map(c=><div key={c.id} className="rounded-lg bg-slate-50 p-4"><p className="font-semibold">{c.code} · {c.name}</p><p className="mt-2 text-xs text-slate-500">{c.enabled?'Đang bật':'Tạm tắt'} · {c.description}</p></div>)}</section>}
 {tab==='documents'&&<section className="mt-6 space-y-5">{(docs.loading||images.loading)&&<p role="status">Đang tải tài liệu…</p>}{(docs.error||images.error)&&<p role="alert" className="text-red-700">{docs.error||images.error}<button className="ml-4 underline" onClick={()=>{docs.reload();images.reload()}}>Thử lại</button></p>}<h2 className="text-xl font-bold">Tài liệu riêng tư</h2>{docs.data?.length===0&&<p className="text-sm text-amber-800">Chưa có tài liệu địa điểm đính kèm.</p>}{docs.data?.map(doc=><a key={doc.id} href={doc.url} target="_blank" rel="noopener noreferrer" className="block rounded-xl border p-5 text-sm text-emerald-700 underline">{doc.name} · {Math.ceil(doc.sizeBytes/1024)} KB{doc.archived&&" · Bản lưu của hồ sơ trước"}</a>)}<h2 className="text-xl font-bold">Hình ảnh cơ sở</h2><div className="grid gap-5 sm:grid-cols-2">{images.data?.map(image=><a href={image.url} target="_blank" rel="noopener noreferrer" key={image.id} className="rounded-xl border p-4 text-sm text-emerald-700 underline">Mở ảnh {image.id.slice(0,8)} · {Math.ceil(image.sizeBytes/1024)} KB</a>)}</div><p className="text-xs text-slate-500">Việc xem tài liệu được ghi vào audit. Tải lại để lấy liên kết xem mới.</p></section>}
 {tab==='history'&&<section className="mt-6 space-y-4">{r.data.reviews.map(review=><article key={review.id} className="rounded-xl border p-5"><p className="font-bold">{reviewLabels[review.state]||review.state}</p><p className="mt-2 text-xs text-slate-500">Nộp {new Date(review.submittedAt).toLocaleString('vi-VN')}</p><p className="mt-4 text-sm">{review.reason}</p><details className="mt-4 text-sm"><summary>Hồ sơ tại lúc gửi duyệt</summary><pre className="mt-3 overflow-x-auto bg-slate-50 p-4 text-xs">{JSON.stringify(review.snapshot,null,2)}</pre></details></article>)}<h2 className="pt-4 text-lg font-bold">Nhật ký thẩm định</h2>{r.data.audit.map(a=><article className="rounded-xl bg-slate-50 p-4 text-sm" key={a.id}>{a.action} · {new Date(a.occurred_at).toLocaleString('vi-VN')}{a.details&&<p className="mt-2 break-all text-xs text-slate-500">{a.details}</p>}</article>)}</section>}
 {f.status==='PENDING_APPROVAL'&&<section className="mt-8 rounded-2xl border p-6"><h2 className="text-xl font-bold">Quyết định kiểm duyệt</h2><div className="mt-5 flex flex-wrap gap-3"><Button onClick={()=>setAction('APPROVE')} className="bg-emerald-600 text-white">Phê duyệt cơ sở</Button><Button variant="outline" onClick={()=>setAction('SUPPLEMENT_REQUIRED')}>Yêu cầu bổ sung</Button><Button variant="outline" onClick={()=>setAction('REJECT')}>Từ chối hồ sơ</Button></div>{action&&<form role="dialog" aria-label="Xác nhận quyết định kiểm duyệt" onSubmit={decide} className="mt-6 space-y-4 rounded-xl bg-slate-50 p-5"><h3 className="font-bold">{action==='APPROVE'?'Phê duyệt và công khai cơ sở':action==='REJECT'?'Từ chối hồ sơ':'Yêu cầu Owner bổ sung hồ sơ'}</h3><label className="grid gap-2 text-sm">Ghi chú và hướng dẫn<textarea name="reason" className="min-h-28 rounded-lg border p-3" required minLength={action==='APPROVE'?2:20} maxLength={2000} disabled={busy}/></label>{error&&<p role="alert" className="text-red-700">{error}</p>}<div className="flex gap-3"><Button type="submit" disabled={busy} className="bg-emerald-600 text-white">{busy?'Đang xử lý…':'Xác nhận quyết định'}</Button><Button variant="outline" onClick={()=>setAction(null)} disabled={busy}>Quay lại</Button></div></form>}</section>}</div>
}
