'use client'
import Link from 'next/link'
import { useState } from 'react'
import { useApi } from '@/lib/use-api'
import { RequireAuth } from '@/features/auth/require-auth'
import { Input } from '@/components/ui/input'
import { Button } from '@/components/ui/button'
import type { Payment } from '@/features/booking/types'
import { money } from '@/features/schedule/types'
import { AdminNav } from './account-list'
export function PaymentMonitor(){return <RequireAuth roles={['ADMIN']}><Loaded/></RequireAuth>}
function Loaded(){const [path,setPath]=useState('/admin/payments');const r=useApi<Payment[]>(path)
 function search(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),p=new URLSearchParams();for(const key of ['q','status','purpose']){const v=String(f.get(key)||'');if(v)p.set(key,v)}setPath(`/admin/payments?${p}`)}
 function exportRows(){if(!r.data)return;const quote=(value:unknown)=>`"${String(value??'').replaceAll('"','""')}"`;const rows=[['paymentId','bookingId','providerReference','purpose','amount','currency','status'],...r.data.map(p=>[p.id,p.bookingId,p.providerReference,p.purpose,p.amount,p.currency,p.status])];const url=URL.createObjectURL(new Blob(['\uFEFF'+rows.map(row=>row.map(quote).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='sporthub-payments.csv';a.click();URL.revokeObjectURL(url)}
 return <div className="mx-auto max-w-6xl px-5 py-10"><div className="flex justify-between gap-4"><h1 className="text-3xl font-black">Giám sát giao dịch</h1><Button variant="outline" onClick={exportRows} disabled={!r.data?.length}>Xuất kết quả hiển thị</Button></div><AdminNav active="payments"/><form onSubmit={search} className="mt-6 grid gap-4 rounded-2xl bg-slate-50 p-5 md:grid-cols-4"><label className="grid gap-2 text-sm">Mã hoặc tham chiếu<Input name="q" placeholder="Payment, booking, mã cổng"/></label><label className="grid gap-2 text-sm">Trạng thái<select name="status" className="h-10 rounded-lg border bg-white px-3"><option value="">Tất cả</option>{['PENDING','SUCCESS','FAILED','EXPIRED'].map(s=><option key={s}>{s}</option>)}</select></label><label className="grid gap-2 text-sm">Nghiệp vụ<select name="purpose" className="h-10 rounded-lg border bg-white px-3"><option value="">Tất cả</option><option value="BOOKING">Đặt sân</option><option value="GROUP_CONTRIBUTION">Góp tiền nhóm</option><option value="TRANSFER">Chuyển nhượng</option></select></label><Button type="submit" className="mt-auto bg-emerald-600 text-white">Tra cứu</Button></form>{r.loading&&<p role="status" className="mt-6">Đang tải giao dịch…</p>}{r.error&&<p role="alert" className="mt-6 text-red-700">{r.error}<button className="ml-4 underline" onClick={r.reload}>Thử lại</button></p>}{r.data?.length===0&&<p className="mt-6 rounded-xl border p-6 text-slate-500">Không có giao dịch phù hợp.</p>}<div className="mt-6 divide-y rounded-2xl border">{r.data?.map(p=><Link key={p.id} href={`/admin/payments/${p.id}`} className="flex flex-wrap justify-between gap-4 p-5 hover:bg-emerald-50"><div><p className="font-bold">{p.providerReference}</p><p className="mt-2 text-sm text-slate-500">{p.purpose} · {p.status}</p></div><strong className="text-emerald-700">{money(p.amount,p.currency)}</strong></Link>)}</div><p className="mt-4 text-xs text-slate-500">Tối đa 200 kết quả. Xuất CSV áp dụng cho danh sách đang hiển thị.</p></div>
}
type PaymentDetail={payment:Payment;audit:unknown[];callbacks:unknown[];requests:unknown[];refunds:{state:string;reason:string;requester_id:string}[];escrow:{state:string;amount:number;currency:string;policy_reference:string}[]}
export function AdminPaymentDetail({id}:{id:string}){return <RequireAuth roles={['ADMIN']}><Detail id={id}/></RequireAuth>}
function Detail({id}:{id:string}){const r=useApi<PaymentDetail>(`/admin/payments/${id}`);const [tab,setTab]=useState('audit');if(r.loading)return <p role="status" className="p-8">Đang tải giao dịch…</p>;if(!r.data)return <p role="alert" className="p-8 text-red-700">{r.error}<button className="ml-4 underline" onClick={r.reload}>Thử lại</button></p>;const p=r.data.payment;const records=tab==='audit'?r.data.audit:tab==='callbacks'?r.data.callbacks:r.data.requests
 return <div className="mx-auto max-w-4xl px-5 py-10"><Link className="text-sm text-slate-500" href="/admin/payments">Giám sát giao dịch</Link><h1 className="mt-5 break-all text-2xl font-black">{p.providerReference}</h1><section className="mt-6 space-y-3 rounded-2xl border p-6"><p className="text-3xl font-bold text-emerald-700">{money(p.amount,p.currency)}</p><p>{p.purpose} · {p.status}</p><p className="break-all text-sm text-slate-500">Người trả {p.payerId}</p><Link href={`/admin/bookings/${p.bookingId}`} className="block text-sm text-emerald-700 underline">Xem booking liên quan</Link></section>{r.data.escrow.map((x,i)=><section key={i} className="mt-5 rounded-xl bg-amber-50 p-5 text-sm text-amber-900"><h2 className="font-bold">Escrow: {x.state}</h2><p className="mt-2">{money(x.amount,x.currency)} · {x.policy_reference}</p></section>)}{r.data.refunds.map((x,i)=><section key={i} className="mt-5 rounded-xl border p-5 text-sm"><p className="font-bold">Yêu cầu hoàn tiền: {x.state}</p><p className="mt-2">{x.reason}</p></section>)}<div role="tablist" aria-label="Bằng chứng giao dịch" className="mt-8 flex gap-3 border-b pb-4">{[['audit','Lịch sử xử lý'],['callbacks','Callback đã xác minh'],['requests','Khóa chống lặp']].map(([value,label])=><button role="tab" aria-selected={tab===value} key={value} onClick={()=>setTab(value)} className={`rounded-full px-4 py-2 text-sm ${tab===value?'bg-emerald-600 text-white':'bg-slate-100'}`}>{label}</button>)}</div><div className="mt-5 space-y-4">{records.map((x,i)=><pre key={i} className="overflow-x-auto rounded-xl bg-slate-50 p-5 text-xs">{JSON.stringify(x,null,2)}</pre>)}</div></div>
}
