'use client'
import Link from 'next/link'
import { useState } from 'react'
import { api } from '@/lib/api'
import { useApi } from '@/lib/use-api'
import { RequireAuth } from '@/features/auth/require-auth'
import { Input } from '@/components/ui/input'
import { Button } from '@/components/ui/button'
import type { Facility } from '@/features/facility/types'
import { type Booking,statusLabels } from '@/features/booking/types'
import { money } from '@/features/schedule/types'
type Access={facilityBindings:{facilityId:string;permissions:string[]}[]}
export function OperationBookings({owner=false}:{owner?:boolean}){return <RequireAuth roles={[owner?'OWNER':'STAFF']}><Loaded owner={owner}/></RequireAuth>}
function Loaded({owner}:{owner:boolean}){
 const owned=useApi<Facility[]>(owner?'/owner/facilities':null);const access=useApi<Access>(owner?null:'/users/me/access');const publicFacilities=useApi<Facility[]>(owner?null:'/facilities');const [selection,setSelection]=useState('');const [filter,setFilter]=useState('')
 const facilities=owner?owned.data:publicFacilities.data?.filter(f=>access.data?.facilityBindings.some(b=>b.facilityId===f.id&&b.permissions.includes('BOOKING_READ')));const facilityId=selection||facilities?.[0]?.id
 const bookings=useApi<Booking[]>(facilityId?`/bookings/facility/${facilityId}`:null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('')
 const can=(permission:string)=>owner||access.data?.facilityBindings.find(b=>b.facilityId===facilityId)?.permissions.includes(permission)
 async function action(booking:Booking,operation:string,token?:string){if(busy)return;if(operation==='complete'&&!window.confirm('Xác nhận khách đã kết thúc và bàn giao sân?'))return;setBusy(true);setError('');setMessage('');try{await api(`/bookings/${booking.id}/${operation}`,{method:'POST',...(token?{body:JSON.stringify({token})}:{})});bookings.reload();setMessage(operation==='check-in'?'Đã check-in khách.':'Đã hoàn tất booking.')}catch(err){setError(err instanceof Error?err.message:'Không thể thực hiện thao tác.')}finally{setBusy(false)}}
 return <div className="mx-auto max-w-6xl px-5 py-10"><div className="flex flex-wrap items-center justify-between gap-4"><h1 className="text-3xl font-black">Vận hành lịch đặt</h1>{!owner&&can('BOOKING_CREATE_COUNTER')&&facilityId&&<Link className="rounded-full bg-emerald-600 px-5 py-2 text-sm text-white" href={`/staff/counter-booking?facilityId=${facilityId}`}>Đặt tại quầy</Link>}</div><div className="my-6 flex flex-wrap gap-4"><label className="grid gap-2 text-sm">Cơ sở<select className="rounded-lg border bg-white p-3" value={facilityId||''} onChange={e=>setSelection(e.target.value)} disabled={busy}>{facilities?.map(f=><option value={f.id} key={f.id}>{f.name}</option>)}</select></label><label className="grid gap-2 text-sm">Trạng thái<select className="rounded-lg border bg-white p-3" value={filter} onChange={e=>setFilter(e.target.value)}><option value="">Tất cả</option>{Object.entries(statusLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><Button className="self-end" variant="outline" onClick={bookings.reload} disabled={busy}>Làm mới</Button></div>
  {(owned.loading||access.loading||publicFacilities.loading||bookings.loading)&&<p role="status">Đang tải lịch đặt…</p>}{(error||owned.error||access.error||publicFacilities.error||bookings.error)&&<p role="alert" className="my-4 text-red-700">{error||owned.error||access.error||publicFacilities.error||bookings.error}</p>}{message&&<p role="status" className="my-4 text-emerald-700">{message}</p>}{facilities?.length===0&&<p className="text-slate-500">Chưa có cơ sở trong phạm vi quản lý với quyền xem booking.</p>}{bookings.data?.filter(b=>!filter||b.status===filter).length===0&&<p className="rounded-xl border p-6 text-slate-500">Chưa có booking phù hợp.</p>}
  <div className="space-y-4">{bookings.data?.filter(b=>!filter||b.status===filter).map(b=><article key={b.id} className="rounded-xl border p-5"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="font-bold">{new Date(b.startsAt).toLocaleString('vi-VN',{timeZone:b.priceSnapshot.timezone})} · {statusLabels[b.status]}</h2><p className="mt-2 text-sm text-slate-500">{b.guestName||'Khách trực tuyến'} {b.guestPhone||''} · {b.id.slice(0,8).toUpperCase()}</p></div><p className="font-bold">{money(b.amount,b.currency)}</p></div>{b.status==='CONFIRMED'&&can('BOOKING_CHECK_IN')&&<form className="mt-5 flex flex-wrap gap-3" onSubmit={e=>{e.preventDefault();action(b,'check-in',String(new FormData(e.currentTarget).get('token')||''))}}><Input name="token" aria-label={`Mã check-in ${b.id.slice(0,8)}`} placeholder="Nhập mã check-in do khách cung cấp" className="min-w-64 flex-1" required disabled={busy}/><Button type="submit" disabled={busy}>Check-in</Button></form>}{b.status==='CHECKED_IN'&&can('BOOKING_COMPLETE')&&<Button className="mt-4" onClick={()=>action(b,'complete')} disabled={busy}>Hoàn tất ca chơi</Button>}</article>)}</div>
 </div>
}
