'use client'
import Link from 'next/link'
import { useEffect,useState } from 'react'
import { useRouter } from 'next/navigation'
import { api } from '@/lib/api'
import { useApi } from '@/lib/use-api'
import { useAuth } from '@/lib/auth-context'
import { RequireAuth } from '@/features/auth/require-auth'
import { Button } from '@/components/ui/button'
import { Countdown } from '@/features/booking/countdown'
import { money } from '@/features/schedule/types'
import type { Facility,Court } from '@/features/facility/types'
import type { Payment } from '@/features/booking/types'
import { type Group,groupStates,memberStates } from './types'
export function GroupDetail({id}:{id:string}){return <RequireAuth roles={['CUSTOMER']}><Loaded id={id}/></RequireAuth>}
function Loaded({id}:{id:string}){
 const router=useRouter();const {user}=useAuth();const r=useApi<Group>(`/groups/${id}`);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [paymentKeys]=useState(()=>new Map<string,string>())
 const facility=useApi<Facility>(r.data?`/facilities/${r.data.booking.facilityId}`:null);const courts=useApi<Court[]>(r.data?`/facilities/${r.data.booking.facilityId}/courts`:null)
 useEffect(()=>{if(r.data?.state!=='GROUP_PENDING')return;const timer=setInterval(r.reload,5000);return()=>clearInterval(timer)},[r.data?.state,r.reload])
 async function pay(memberId:string){if(busy)return;setBusy(true);setError('');if(!paymentKeys.has(memberId))paymentKeys.set(memberId,crypto.randomUUID());try{const p=await api<Payment>('/payments',{method:'POST',headers:{'Idempotency-Key':paymentKeys.get(memberId)!},body:JSON.stringify({bookingId:id,memberId})});if(p.status==='FAILED'||p.status==='EXPIRED'){paymentKeys.delete(memberId);throw new Error('Giao dịch trước đã kết thúc. Bấm thanh toán để tạo giao dịch mới.')}router.push(`/customer/payments/${p.id}`)}catch(err){setError(err instanceof Error?err.message:'Không thể tạo giao dịch.')}finally{setBusy(false)}}
 async function act(action:'leave'|'cancel'){if(!window.confirm(action==='leave'?'Rời nhóm và yêu cầu chia lại chi phí?':'Hủy nhóm đặt sân này?'))return;setBusy(true);setError('');try{await api(`/groups/${id}/${action}`,{method:'POST',body:action==='cancel'?JSON.stringify({reason:'Booking Owner cancelled the unpaid group'}):undefined});if(action==='leave')router.push('/customer/groups');else r.reload()}catch(err){setError(err instanceof Error?err.message:'Không thể cập nhật nhóm.')}finally{setBusy(false)}}
 if(r.loading&&!r.data)return <p className="p-8" role="status">Đang tải nhóm…</p>
 if(!r.data)return <p className="p-8 text-red-700" role="alert">{r.error}<button className="ml-4 underline" onClick={r.reload}>Thử lại</button></p>
 const g=r.data;const owner=user?.id===g.ownerId;const pending=g.state==='GROUP_PENDING';const total=g.booking.amount;const locked=g.members.some(m=>m.amountPaid>0||m.paymentRequestedAt!==null)
 return <div className="mx-auto max-w-4xl px-5 py-10"><Link className="text-sm text-slate-500" href="/customer/groups">Nhóm đặt sân / {g.name}</Link><div className="mt-5 flex flex-wrap items-center justify-between gap-4"><h1 className="text-3xl font-black">{g.name}</h1><span className="rounded-full bg-emerald-50 px-4 py-2 text-sm font-semibold text-emerald-700">{groupStates[g.state]}</span></div><section className="mt-6 rounded-2xl border p-6"><h2 className="text-xl font-bold">{facility.data?.name||'Cơ sở'} · {courts.data?.find(c=>c.id===g.booking.courtId)?.name||'Sân'}</h2><p className="mt-3 text-sm text-slate-500">{new Date(g.booking.startsAt).toLocaleString('vi-VN',{timeZone:g.booking.priceSnapshot.timezone})} → {new Date(g.booking.endsAt).toLocaleTimeString('vi-VN',{timeZone:g.booking.priceSnapshot.timezone})}</p>{pending&&<div className="mt-4"><Countdown expiresAt={g.deadline}/></div>}<p className="mt-5 font-bold">Đã đóng {money(g.totalPaid)} / {money(total)}</p><progress className="mt-3 h-3 w-full accent-emerald-600" value={g.totalPaid} max={total} aria-label="Tiến độ thanh toán nhóm"/><p className="mt-3 text-sm text-slate-500">{g.allocationsLocked?'Danh sách đã chốt; mỗi người thanh toán phần được phân bổ.':'Chờ thành viên tham gia và người tổ chức chia tiền.'}</p></section>
  {owner&&pending&&<nav aria-label="Quản lý nhóm" className="mt-6 flex flex-wrap gap-3">{!g.allocationsLocked&&<Link href={`/customer/groups/${id}/invite`} className="rounded-full border px-5 py-3 text-sm">Mời thành viên</Link>}{!locked&&<Link href={`/customer/groups/${id}/split`} className="rounded-full bg-emerald-600 px-5 py-3 text-sm text-white">{g.allocationsLocked?'Điều chỉnh phân chia':'Phân chia chi phí'}</Link>}<Button variant="outline" disabled={busy||locked} onClick={()=>act('cancel')}>Hủy nhóm</Button></nav>}
  {(error||r.error)&&<p role="alert" className="mt-5 rounded-lg bg-red-50 p-4 text-sm text-red-700">{error||r.error}</p>}<h2 className="mt-8 text-xl font-bold">Thành viên · {g.members.length}/{g.maxMembers}</h2><div className="mt-4 divide-y rounded-2xl border">{g.members.map(m=><div className="flex flex-wrap items-center justify-between gap-4 p-5" key={m.id}><div><p className="font-semibold">{m.displayName} {m.userId===g.ownerId&&<span className="ml-2 text-xs text-emerald-700">Người tổ chức</span>}</p><p className="mt-1 text-sm text-slate-500">{g.allocationsLocked&&m.amountDue===0?'Không cần đóng':memberStates[m.paymentState]} · {money(m.amountPaid)} / {money(m.amountDue)}</p></div>{pending&&g.allocationsLocked&&m.amountDue>0&&m.amountPaid===0&&(owner||m.userId===user?.id)&&<Button disabled={busy} onClick={()=>pay(m.id)} className="bg-emerald-600 text-white">{m.userId===user?.id?'Đóng phần của tôi':'Thanh toán thay'}</Button>}</div>)}</div>
  {!owner&&pending&&<Button className="mt-5" variant="outline" disabled={busy||locked} onClick={()=>act('leave')}>Rời nhóm</Button>}{g.state==='CONFIRMED'&&owner&&<Link className="mt-6 block rounded-full bg-emerald-600 p-3 text-center text-white" href={`/customer/bookings/${id}`}>Mở booking và mã check-in</Link>}{g.state==='GROUP_EXPIRED'&&<p className="mt-6 rounded-xl bg-amber-50 p-5 text-sm text-amber-800">Sân đã được giải phóng. Khoản đóng góp đã nhận được lưu để đối soát và xem xét hoàn tiền theo chính sách được duyệt.</p>}
 </div>
}
