ALTER TABLE users ALTER COLUMN email DROP NOT NULL;
ALTER TABLE users ADD CONSTRAINT chk_user_contact CHECK (email IS NOT NULL OR phone IS NOT NULL);
ALTER TABLE otp_codes ADD COLUMN recipient VARCHAR(255);
ALTER TABLE otp_codes DROP CONSTRAINT chk_otp_purpose;
ALTER TABLE otp_codes ADD CONSTRAINT chk_otp_purpose
 CHECK (purpose IN ('EMAIL_VERIFY','PHONE_VERIFY','EMAIL_CHANGE','PHONE_CHANGE','PASSWORD_RESET'));
ALTER TABLE staff_permissions ALTER COLUMN permission TYPE VARCHAR(64);
