'use client'
import { useState } from 'react'
import { api } from '@/lib/api'
import { useApi } from '@/lib/use-api'
import { Button } from '@/components/ui/button'
import { useFacility } from './facility-context'
export type ReviewDocument={id:string;name:string;url:string;contentType:string;sizeBytes:number;archived:boolean}
export function FacilityDocumentPage(){const {facility}=useFacility();const r=useApi<ReviewDocument[]>(`/owner/facilities/${facility.id}/documents`);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [remove,setRemove]=useState<string|null>(null);const editable=!['PENDING_APPROVAL','REJECTED'].includes(facility.status)
 async function upload(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;const form=e.currentTarget;setBusy(true);setError('');try{await api(`/owner/facilities/${facility.id}/documents`,{method:'POST',body:new FormData(form)});form.reset();r.reload()}catch(err){setError(err instanceof Error?err.message:'Không thể tải tài liệu.')}finally{setBusy(false)}}
 async function deleteFile(id:string){setBusy(true);setError('');try{await api(`/owner/facilities/${facility.id}/documents/${id}`,{method:'DELETE'});setRemove(null);r.reload()}catch(err){setError(err instanceof Error?err.message:'Không thể gỡ tài liệu.')}finally{setBusy(false)}}
 return <div className="max-w-4xl"><h2 className="text-2xl font-bold">Tài liệu thẩm định</h2><p className="mt-3 text-slate-500">Tải giấy tờ địa điểm, hợp đồng thuê hoặc sử dụng mặt bằng. Chỉ Owner sở hữu và Admin thẩm định được xem tài liệu này.</p>{editable&&<form onSubmit={upload} className="mt-6 flex flex-wrap items-end gap-4 rounded-2xl border p-6"><label className="grid gap-3 text-sm font-medium">Tài liệu PDF, JPEG hoặc PNG · tối đa 10 MB<input className="block rounded-lg border p-3 text-sm" name="file" type="file" accept="application/pdf,image/jpeg,image/png" required disabled={busy}/></label><Button type="submit" disabled={busy} className="bg-emerald-600 text-white">{busy?'Đang xử lý…':'Tải tài liệu'}</Button></form>}{!editable&&<p className="mt-5 rounded-xl bg-amber-50 p-5 text-sm text-amber-900">Tài liệu của hồ sơ đã gửi được giữ nguyên. Khi cần bổ sung, Admin sẽ mở lại hồ sơ.</p>}{error&&<p role="alert" className="mt-5 text-red-700">{error}</p>}{r.loading&&<p role="status" className="mt-6">Đang tải tài liệu…</p>}{r.error&&<p role="alert" className="mt-6 text-red-700">{r.error}<button className="ml-3 underline" onClick={r.reload}>Thử lại</button></p>}{r.data?.length===0&&<p className="mt-6 rounded-xl border border-dashed p-6 text-slate-500">Chưa có tài liệu đính kèm.</p>}<div className="mt-6 space-y-4">{r.data?.map(doc=><article className="rounded-xl border p-5" key={doc.id}><div className="flex flex-wrap justify-between gap-4"><div><a href={doc.url} target="_blank" rel="noopener noreferrer" className="font-bold text-emerald-700 underline">{doc.name}</a><p className="mt-2 text-xs text-slate-500">{doc.contentType} · {Math.ceil(doc.sizeBytes/1024)} KB</p></div>{editable&&<Button variant="outline" onClick={()=>setRemove(doc.id)} disabled={busy}>Gỡ tài liệu</Button>}</div>{remove===doc.id&&<div role="dialog" aria-label="Gỡ tài liệu đính kèm" className="mt-4 rounded-lg bg-amber-50 p-4"><p className="text-sm">Gỡ {doc.name} khỏi hồ sơ đang chuẩn bị?</p><div className="mt-4 flex gap-3"><Button onClick={()=>deleteFile(doc.id)} disabled={busy}>Xác nhận gỡ</Button><Button variant="outline" onClick={()=>setRemove(null)} disabled={busy}>Giữ lại</Button></div></div>}</article>)}</div><p className="mt-4 text-xs text-slate-500">Liên kết xem tài liệu có hiệu lực 5 phút. Tải lại danh sách để lấy liên kết mới.</p></div>
}
