'use client'
import Link from 'next/link'
import { useState } from 'react'
import { api } from '@/lib/api'
import { useApi } from '@/lib/use-api'
import { Button } from '@/components/ui/button'
import { useFacility } from './facility-context'
export type FacilityReview={id:string;facilityId:string;ownerId:string;state:string;snapshot:unknown;submittedAt:string;reviewedAt:string|null;reviewedBy:string|null;reason:string|null}
export const reviewLabels:Record<string,string>={DRAFT:'Bản nháp',PENDING_APPROVAL:'Chờ kiểm duyệt',ACTIVE:'Đang hoạt động',APPROVED:'Đã phê duyệt',REJECTED:'Đã từ chối',SUPPLEMENT_REQUIRED:'Cần bổ sung',SUSPENDED:'Tạm ngừng'}
export function FacilityReviewPage(){const {facility,reload}=useFacility();const r=useApi<FacilityReview[]>(`/owner/facilities/${facility.id}/reviews`);const [confirm,setConfirm]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('')
 async function submit(){if(busy)return;setBusy(true);setError('');try{await api(`/owner/facilities/${facility.id}/submit`,{method:'POST'});setConfirm(false);r.reload();reload()}catch(err){setError(err instanceof Error?err.message:'Không thể gửi hồ sơ.')}finally{setBusy(false)}}
 return <div className="max-w-3xl"><h2 className="text-2xl font-bold">Kiểm duyệt cơ sở</h2><p className="mt-3 text-slate-500">Hoàn thiện hồ sơ, thêm sân và khai báo lịch mở cửa trước khi gửi. Hồ sơ được giữ nguyên trong thời gian Admin thẩm định.</p><section className="mt-6 rounded-2xl border p-6"><p className="font-bold text-emerald-700">{reviewLabels[facility.status]||facility.status}</p><div className="mt-5 flex flex-wrap gap-4 text-sm text-emerald-700"><Link href={`/owner/facilities/${facility.id}/edit`} className="underline">Thông tin cơ sở</Link><Link href={`/owner/facilities/${facility.id}/courts`} className="underline">Danh sách sân</Link><Link href={`/owner/facilities/${facility.id}/schedule`} className="underline">Lịch mở cửa</Link><Link href={`/owner/facilities/${facility.id}/documents`} className="underline">Tài liệu thẩm định riêng tư</Link></div>{facility.status==='DRAFT'&&<Button onClick={()=>setConfirm(true)} className="mt-6 bg-emerald-600 text-white">Gửi kiểm duyệt</Button>}{facility.status==='REJECTED'&&<p className="mt-4 text-sm text-amber-800">Hồ sơ đã bị từ chối. Tạo một cơ sở mới để nộp lại thông tin đầy đủ.</p>}</section>
 {confirm&&<section role="dialog" aria-label="Xác nhận gửi hồ sơ" className="mt-5 rounded-2xl bg-emerald-50 p-6"><h3 className="font-bold">Gửi hồ sơ {facility.name}</h3><p className="mt-3 text-sm text-slate-600">Admin sẽ xem thông tin cơ sở, sân, lịch mở cửa và tài liệu đính kèm. Bạn có thể sửa hồ sơ khi Admin yêu cầu bổ sung.</p><div className="mt-5 flex gap-3"><Button onClick={submit} disabled={busy} className="bg-emerald-600 text-white">{busy?'Đang gửi…':'Xác nhận gửi'}</Button><Button variant="outline" onClick={()=>setConfirm(false)} disabled={busy}>Quay lại</Button></div></section>}
 {error&&<p role="alert" className="mt-5 text-red-700">{error}</p>}{r.loading&&<p role="status" className="mt-6">Đang tải lịch sử kiểm duyệt…</p>}{r.error&&<p role="alert" className="mt-6 text-red-700">{r.error}<button className="ml-4 underline" onClick={r.reload}>Thử lại</button></p>}<h3 className="mt-8 text-lg font-bold">Lịch sử hồ sơ</h3>{r.data?.length===0&&<p className="mt-4 text-sm text-slate-500">Cơ sở chưa gửi hồ sơ kiểm duyệt.</p>}<div className="mt-5 space-y-4">{r.data?.map(review=><article key={review.id} className="rounded-xl border p-5"><p className="font-bold">{reviewLabels[review.state]||review.state}</p><p className="mt-2 text-xs text-slate-500">Nộp {new Date(review.submittedAt).toLocaleString('vi-VN')}{review.reviewedAt&&` · Xử lý ${new Date(review.reviewedAt).toLocaleString('vi-VN')}`}</p>{review.reason&&<p className="mt-4 text-sm">{review.reason}</p>}</article>)}</div></div>
}
