'use client'
import { useState } from 'react'
import { api } from '@/lib/api'
import { useApi } from '@/lib/use-api'
import { useFacility } from './facility-context'
import { Input } from '@/components/ui/input'
import { Button } from '@/components/ui/button'
type Binding={id:string;userId:string;fullName:string;email:string;active:boolean;permissions:string[]}
const permissions:Record<string,string>={BOOKING_READ:'Xem lịch đặt',BOOKING_CREATE_COUNTER:'Tạo booking tại quầy',BOOKING_CHECK_IN:'Check-in',BOOKING_COMPLETE:'Hoàn tất booking',SCHEDULE_READ:'Xem lịch và giá'}
export function FacilityStaffPage(){const {facility}=useFacility();const resource=useApi<Binding[]>(`/staff-bindings/facilities/${facility.id}`);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('')
 async function assign(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;setBusy(true);setError('');setMessage('');const form=e.currentTarget;const values=new FormData(form);try{await api(`/staff-bindings/facilities/${facility.id}`,{method:'POST',body:JSON.stringify({identifier:values.get('identifier'),permissions:values.getAll('permissions')})});resource.reload();form.reset();setMessage('Đã cập nhật phân công và quyền tại cơ sở.')}catch(err){setError(err instanceof Error?err.message:'Không thể phân công.')}finally{setBusy(false)}}
 async function revoke(id:string){if(!window.confirm('Thu hồi quyền làm việc tại cơ sở của nhân viên này?'))return;setBusy(true);setError('');try{await api(`/staff-bindings/facilities/${facility.id}/${id}`,{method:'DELETE'});resource.reload()}catch(err){setError(err instanceof Error?err.message:'Không thể thu hồi.')}finally{setBusy(false)}}
 return <section><h2 className="text-2xl font-bold">Nhân viên tại cơ sở</h2><p className="mt-3 text-sm text-slate-500">Phân công tài khoản có vai trò Staff và cấp từng quyền vận hành.</p><form className="my-6 max-w-2xl space-y-4 rounded-xl border p-5" onSubmit={assign}><label className="grid gap-2 text-sm">Email hoặc số điện thoại Staff<Input name="identifier" required disabled={busy}/></label><fieldset disabled={busy} className="grid gap-3 sm:grid-cols-2"><legend className="mb-3 text-sm font-semibold">Quyền tại cơ sở</legend>{Object.entries(permissions).map(([name,label])=><label key={name} className="flex items-center gap-3 text-sm"><input type="checkbox" name="permissions" value={name}/>{label}</label>)}</fieldset><Button type="submit" disabled={busy}>{busy?'Đang lưu…':'Lưu phân công'}</Button></form>{(resource.error||error)&&<p role="alert" className="text-red-700">{error||resource.error}</p>}{message&&<p role="status" className="text-emerald-700">{message}</p>}{resource.loading&&<p role="status">Đang tải nhân viên…</p>}{resource.data?.length===0&&<p className="text-slate-500">Chưa có nhân viên được phân công.</p>}<div className="mt-5 space-y-3">{resource.data?.map(b=><article key={b.id} className="flex flex-wrap items-center justify-between gap-4 rounded-xl border p-5"><div><h3 className="font-bold">{b.fullName} · {b.active?'Đang làm việc':'Đã thu hồi'}</h3><p className="mt-2 text-sm text-slate-500">{b.email}</p><p className="mt-2 text-xs text-slate-500">{b.permissions.map(p=>permissions[p]||p).join(' · ')}</p></div>{b.active&&<button onClick={()=>revoke(b.id)} disabled={busy} className="text-sm text-red-700">Thu hồi</button>}</article>)}</div></section>
}
