'use client'
import Link from 'next/link'
import { useEffect,useState } from 'react'
import { useRouter } from 'next/navigation'
import { api } from '@/lib/api'
import { useApi } from '@/lib/use-api'
import { RequireAuth } from '@/features/auth/require-auth'
import { Button } from '@/components/ui/button'
import { money } from '@/features/schedule/types'
import { useRemaining } from '@/features/booking/countdown'
import { type Listing,type Acquisition,transferStates } from './types'
export function ListingDetail({id}:{id:string}){return <RequireAuth roles={['CUSTOMER']}><Loaded id={id}/></RequireAuth>}
function Loaded({id}:{id:string}){const router=useRouter();const r=useApi<Listing>(`/transfers/${id}`);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const remaining=useRemaining(r.data?.deadline)
 useEffect(()=>{const timer=setInterval(r.reload,10000);return()=>clearInterval(timer)},[r.reload])
 async function acquire(){if(busy)return;setBusy(true);setError('');try{const a=await api<Acquisition>(`/transfers/${id}/acquisitions`,{method:'POST',headers:{'Idempotency-Key':crypto.randomUUID()}});router.push(`/customer/transfers/acquisitions/${a.id}`)}catch(err){setError(err instanceof Error?err.message:'Không thể giữ giao dịch.');r.reload()}finally{setBusy(false)}}
 async function withdraw(){if(!window.confirm('Rút tin này khỏi chợ chuyển nhượng? Booking của bạn vẫn được giữ.'))return;setBusy(true);setError('');try{await api(`/transfers/${id}/withdraw`,{method:'POST'});r.reload()}catch(err){setError(err instanceof Error?err.message:'Không thể rút tin.')}finally{setBusy(false)}}
 if(r.loading)return <p role="status" className="p-8">Đang tải lượt chuyển nhượng…</p>;if(!r.data)return <p role="alert" className="p-8 text-red-700">{r.error}<button className="ml-4 underline" onClick={r.reload}>Thử lại</button></p>;const l=r.data
 return <div className="mx-auto max-w-3xl px-5 py-10"><Link className="text-sm text-slate-500" href="/transfers">Chợ chuyển nhượng / Chi tiết</Link><div className="mt-6 flex items-center justify-between gap-4"><h1 className="text-3xl font-black">{l.venue.facilityName}</h1><span className="rounded-full bg-emerald-50 px-4 py-2 text-sm text-emerald-700">{transferStates[l.state]}</span></div><p className="mt-4 text-slate-500">{l.venue.courtName} · {l.venue.address}</p><section className="mt-6 space-y-5 rounded-2xl border p-6"><p>{new Date(l.startsAt).toLocaleString('vi-VN',{timeZone:l.venue.timezone})} → {new Date(l.endsAt).toLocaleTimeString('vi-VN',{timeZone:l.venue.timezone})}</p><div className="flex items-baseline gap-4"><strong className="text-3xl text-emerald-700">{money(l.price,l.currency)}</strong><span className="text-slate-400 line-through">{money(l.originalAmount,l.currency)}</span></div><div className="flex flex-wrap gap-2">{l.venue.amenities.map(a=><span key={a} className="rounded-full bg-slate-100 px-3 py-1 text-sm">{a}</span>)}</div><p className="text-sm text-amber-800">Hạn nhận lượt đặt: {new Date(l.deadline).toLocaleString('vi-VN',{timeZone:l.venue.timezone})}</p></section><section className="mt-6 rounded-2xl bg-amber-50 p-6 text-sm text-amber-900"><h2 className="font-bold">Điều kiện nhận lượt đặt</h2><p className="mt-3">Bạn nhận đúng sân và khung giờ trên tin. Quyền sử dụng và mã check-in được chuyển sau khi thanh toán được xác minh và bàn giao hoàn tất.</p><p className="mt-3">Tiền chuyển nhượng được giữ để đối soát; quy tắc tất toán cho người bán đang chờ được chốt.</p></section>{(error||r.error)&&<p role="alert" className="mt-5 text-red-700">{error||r.error}</p>}<div className="mt-6 flex flex-wrap gap-3">{l.own?<>{l.state==='ACTIVE'&&<><Link href={`/customer/transfers/${id}/edit`} className="rounded-full bg-emerald-600 px-5 py-3 text-sm text-white">Sửa tin</Link><Button variant="outline" onClick={withdraw} disabled={busy}>Rút tin</Button></>}<Link href="/customer/transfers" className="p-3 text-sm text-emerald-700">Quản lý tin</Link></>:<Button className="h-12 bg-emerald-600 px-6 text-white" onClick={acquire} disabled={busy||!l.available||remaining===0}>{busy?'Đang giữ giao dịch…':l.available?'Nhận lượt đặt này':'Lượt đặt hiện không khả dụng'}</Button>}</div></div>
}
