'use client'
import Link from 'next/link'
import { useState } from 'react'
import { useApi } from '@/lib/use-api'
import { RequireAuth } from '@/features/auth/require-auth'
import { Input } from '@/components/ui/input'
import { Button } from '@/components/ui/button'
import { money } from '@/features/schedule/types'
import type { Category } from '@/features/facility/types'
import type { Listing } from './types'
export function TransferMarket(){return <RequireAuth roles={['CUSTOMER']}><Loaded/></RequireAuth>}
function Loaded(){const [query,setQuery]=useState('');const [path,setPath]=useState('/transfers');const categories=useApi<Category[]>('/sport-categories');const r=useApi<Listing[]>(path)
 function search(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);const p=new URLSearchParams();for(const k of ['q','category','maxPrice','sort']){const value=String(form.get(k)||'');if(value)p.set(k,value)}if(form.get('date')){const date=String(form.get('date'));p.set('after',`${date}T00:00:00+07:00`);p.set('before',`${date}T23:59:59+07:00`)}setPath(`/transfers?${p}`)}
 return <div className="mx-auto max-w-6xl px-5 py-10"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-sm font-bold text-emerald-700">SPORTHUB MARKETPLACE</p><h1 className="mt-3 text-3xl font-black">Nhận lại lượt đặt sân</h1><p className="mt-3 text-slate-500">Chọn lịch phù hợp từ các lượt đặt đã thanh toán.</p></div><Link className="rounded-full border px-5 py-3 text-sm" href="/customer/transfers">Tin và giao dịch của tôi</Link></div>
 <form onSubmit={search} className="mt-8 grid gap-4 rounded-2xl bg-slate-50 p-5 sm:grid-cols-3"><label className="grid gap-2 text-sm">Khu vực hoặc sân<Input name="q" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Tên sân, tỉnh hoặc quận"/></label><label className="grid gap-2 text-sm">Môn thể thao<select name="category" className="h-10 rounded-lg border bg-white px-3"><option value="">Tất cả</option>{categories.data?.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><label className="grid gap-2 text-sm">Ngày chơi<Input name="date" type="date"/></label><label className="grid gap-2 text-sm">Giá tối đa (VND)<Input name="maxPrice" type="number" min={0} step={1000}/></label><label className="grid gap-2 text-sm">Sắp xếp<select name="sort" className="h-10 rounded-lg border bg-white px-3"><option value="start">Giờ chơi gần nhất</option><option value="price">Giá thấp nhất</option><option value="discount">Mức giảm cao nhất</option></select></label><Button type="submit" className="mt-auto bg-emerald-600 text-white">Tìm lượt đặt</Button></form>
 {r.loading&&<p role="status" className="mt-8">Đang tải chợ chuyển nhượng…</p>}{r.error&&<p role="alert" className="mt-8 text-red-700">{r.error}<button className="ml-4 underline" onClick={r.reload}>Thử lại</button></p>}{r.data?.length===0&&<p className="mt-8 rounded-2xl border p-8 text-slate-500">Chưa có lượt đặt phù hợp. Thử đổi bộ lọc hoặc tìm sân để đặt trực tiếp.</p>}<div className="mt-8 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{r.data?.map(l=><ListingCard key={l.id} listing={l}/>)}</div></div>
}
export function ListingCard({listing:l}:{listing:Listing}){return <Link href={`/transfers/${l.id}`} className="rounded-2xl border p-6 transition hover:border-emerald-500"><div className="flex justify-between gap-3"><span className="text-xs font-bold text-emerald-700">{l.own?'TIN CỦA BẠN':`GIẢM ${Math.round((1-l.price/l.originalAmount)*100)}%`}</span><span className="text-xs text-slate-500">{l.venue.district} · {l.venue.province}</span></div><h2 className="mt-4 text-xl font-bold">{l.venue.facilityName}</h2><p className="mt-2 text-sm text-slate-500">{l.venue.courtName}</p><p className="mt-4 text-sm">{new Date(l.startsAt).toLocaleString('vi-VN',{timeZone:l.venue.timezone})} → {new Date(l.endsAt).toLocaleTimeString('vi-VN',{timeZone:l.venue.timezone,hour:'2-digit',minute:'2-digit'})}</p><div className="mt-6 flex items-baseline gap-3"><strong className="text-2xl text-emerald-700">{money(l.price,l.currency)}</strong><span className="text-sm text-slate-400 line-through">{money(l.originalAmount,l.currency)}</span></div></Link>}
