package com.sporthub.identity.service;
import static com.sporthub.identity.web.dto.AdminAccountDtos.*;
import com.sporthub.identity.domain.*;
import com.sporthub.identity.repository.UserRepository;
import com.sporthub.identity.security.AuthenticatedUser;
import com.sporthub.identity.exception.IdentityException;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.stereotype.Service;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.scheduling.annotation.Scheduled;
import java.time.Instant;
import java.util.*;

@Service @Transactional(readOnly=true)
public class AdminAccountService {
 private final UserRepository users;private final JdbcTemplate jdbc;private final ObjectMapper json;
 public AdminAccountService(UserRepository users,JdbcTemplate jdbc,ObjectMapper json){this.users=users;this.jdbc=jdbc;this.json=json;}
 public List<Account> search(String q,AccountStatus status,Role role,AuthenticatedUser actor){admin(actor);String pattern="%"+(q==null?"":q.trim().toLowerCase(Locale.ROOT))+"%";
  return jdbc.queryForList("SELECT u.id FROM users u LEFT JOIN user_profiles p ON p.user_id=u.id WHERE (lower(COALESCE(u.email,'')) LIKE ? OR COALESCE(u.phone,'') LIKE ? OR lower(COALESCE(p.full_name,'')) LIKE ?) AND (?::varchar IS NULL OR u.status=?::varchar) AND (?::varchar IS NULL OR EXISTS(SELECT 1 FROM user_roles r WHERE r.user_id=u.id AND r.role=?::varchar)) ORDER BY u.created_at DESC LIMIT 100",UUID.class,pattern,pattern,pattern,status==null?null:status.name(),status==null?null:status.name(),role==null?null:role.name(),role==null?null:role.name()).stream().map(id->view(load(id))).toList();
 }
 public Detail detail(UUID id,AuthenticatedUser actor){admin(actor);var account=view(load(id));var sessions=jdbc.query("SELECT id,device_info,ip_address,created_at,expires_at,revoked FROM refresh_tokens WHERE user_id=? ORDER BY created_at DESC LIMIT 100",(r,n)->new Session(r.getObject("id",UUID.class),r.getString("device_info"),r.getString("ip_address"),r.getTimestamp("created_at").toInstant(),r.getTimestamp("expires_at").toInstant(),r.getBoolean("revoked")),id);
  var audit=jdbc.query("SELECT * FROM audit_log WHERE entity_type='USER' AND entity_id=? ORDER BY created_at DESC LIMIT 100",(r,n)->new Audit(r.getObject("id",UUID.class),r.getObject("user_id",UUID.class),r.getString("action"),read(r.getString("old_value")),read(r.getString("new_value")),r.getTimestamp("created_at").toInstant()),id);return new Detail(account,sessions,audit);
 }
 @Transactional public Account lock(UUID id,LockInput input,AuthenticatedUser actor,RequestMetadata metadata){admin(actor);serialize();var user=editable(id,actor);if(user.getStatus()!=AccountStatus.ACTIVE&&user.getStatus()!=AccountStatus.LOCKED)throw conflict("Only verified active or locked accounts can be locked");var before=view(user);Instant now=Instant.now();user.setStatus(AccountStatus.LOCKED);user.setLockedAt(now);user.setLockedUntil(switch(input.duration()){case "SEVEN_DAYS"->now.plusSeconds(7*86400L);case "THIRTY_DAYS"->now.plusSeconds(30*86400L);case "PERMANENT"->null;default->throw new IllegalArgumentException("Invalid lock duration");});user.setLockReason(input.reason().trim());user.setUpdatedBy(actor.userId());users.saveAndFlush(user);revoke(id);var after=view(user);audit(user,actor.userId(),"ADMIN_ACCOUNT_LOCKED",before,after,metadata);notice(user,"SportHub account locked","Your account is locked. Reason: "+input.reason()+". Until: "+Objects.toString(user.getLockedUntil(),"permanent"));return after;}
 @Transactional public Account unlock(UUID id,Reason input,AuthenticatedUser actor,RequestMetadata metadata){admin(actor);serialize();var user=editable(id,actor);if(user.getStatus()!=AccountStatus.LOCKED)throw conflict("Account is not locked");var before=view(user);user.setStatus(AccountStatus.ACTIVE);user.setLockedAt(null);user.setLockedUntil(null);user.setLockReason(null);user.setUpdatedBy(actor.userId());users.saveAndFlush(user);var after=view(user);audit(user,actor.userId(),"ADMIN_ACCOUNT_UNLOCKED",before,Map.of("account",after,"reason",input.reason()),metadata);notice(user,"SportHub account unlocked","Your account is active again. Please sign in to create a new session.");return after;}
 @Transactional public Account roles(UUID id,RolesInput input,AuthenticatedUser actor,RequestMetadata metadata){admin(actor);serialize();var user=editable(id,actor);if(user.getStatus()==AccountStatus.PENDING_VERIFICATION)throw conflict("Unverified accounts cannot receive roles");if(input.roles()==null||input.roles().isEmpty())throw conflict("An account must retain at least one role");var before=view(user);if(user.getRoles().equals(input.roles()))return before;user.setRoles(new LinkedHashSet<>(input.roles()));user.setUpdatedBy(actor.userId());users.saveAndFlush(user);revoke(id);var after=view(user);audit(user,actor.userId(),"ADMIN_ROLES_CHANGED",before,Map.of("account",after,"reason",input.reason()),metadata);notice(user,"SportHub roles updated","Your roles are now "+user.getRoles()+". Sign in again to use the updated access.");return after;}
 @Scheduled(fixedDelayString="${sporthub.identity.admin-expiry-delay-ms:60000}",initialDelayString="${sporthub.identity.admin-expiry-delay-ms:60000}") @Transactional public void expireLocks(){serialize();var ids=jdbc.queryForList("SELECT id FROM users WHERE status='LOCKED' AND locked_until<=NOW()",UUID.class);for(var id:ids){var user=load(id);var before=view(user);user.setStatus(AccountStatus.ACTIVE);user.setLockedAt(null);user.setLockedUntil(null);user.setLockReason(null);users.saveAndFlush(user);audit(user,null,"ACCOUNT_LOCK_EXPIRED",before,view(user),new RequestMetadata(null,"system-expiry"));notice(user,"SportHub account unlocked","Your temporary lock has expired. Sign in to create a new session.");}}
 public List<Map<String,Object>> statistics(AuthenticatedUser actor){admin(actor);return jdbc.queryForList("SELECT status,count(*) AS total FROM users GROUP BY status ORDER BY status");}
 private void serialize(){jdbc.queryForObject("SELECT pg_advisory_xact_lock(hashtextextended('identity-admin-account-controls',0))",Object.class);}
 private User editable(UUID id,AuthenticatedUser actor){var user=load(id);if(id.equals(actor.userId()))throw conflict("You cannot lock or change your own Admin account");if(user.getRoles().contains(Role.ADMIN))throw conflict("BLOCKED_RULE: Admin-to-Admin changes require an approved hierarchy policy");return user;}
 private void admin(AuthenticatedUser actor){if(actor==null||!actor.roles().contains(Role.ADMIN))throw new IdentityException(HttpStatus.FORBIDDEN,"IDENTITY-ADMIN-REQUIRED","Admin role required");}
 private User load(UUID id){return users.findById(id).orElseThrow(()->new IdentityException(HttpStatus.NOT_FOUND,"IDENTITY-USER-NOT-FOUND","Account not found"));}
 private Account view(User u){return new Account(u.getId(),u.getProfile()==null?"":u.getProfile().getFullName(),u.getEmail(),u.getPhone(),u.isEmailVerified(),u.isPhoneVerified(),Set.copyOf(u.getRoles()),u.getStatus(),u.getCreatedAt(),u.getLastLoginAt(),u.getLockedAt(),u.getLockedUntil(),u.getLockReason());}
 private void revoke(UUID id){jdbc.update("UPDATE refresh_tokens SET revoked=true,revoked_at=NOW() WHERE user_id=? AND NOT revoked",id);}
 private void notice(User user,String subject,String body){String recipient=user.isEmailVerified()?user.getEmail():user.isPhoneVerified()?user.getPhone():null;if(recipient!=null)jdbc.update("INSERT INTO identity_notifications(id,user_id,recipient,subject,body) VALUES(?,?,?,?,?)",UUID.randomUUID(),user.getId(),recipient,subject,body);}
 private void audit(User user,UUID actor,String action,Object before,Object after,RequestMetadata metadata){jdbc.update("INSERT INTO audit_log(id,user_id,action,entity_type,entity_id,old_value,new_value,ip_address,user_agent) VALUES(?,?,?,'USER',?,?::jsonb,?::jsonb,?,?)",UUID.randomUUID(),actor,action,user.getId(),write(before),write(after),metadata.ipAddress(),metadata.userAgent());}
 private String write(Object value){try{return json.writeValueAsString(value);}catch(Exception ex){throw new IllegalStateException(ex);}}
 private com.fasterxml.jackson.databind.JsonNode read(String value){try{return value==null?null:json.readTree(value);}catch(Exception ex){throw new IllegalStateException(ex);}}
 private IdentityException conflict(String message){return new IdentityException(HttpStatus.CONFLICT,"IDENTITY-ADMIN-CONFLICT",message);}
}
