'use client'
import Link from 'next/link'
import { useState } from 'react'
import { api } from '@/lib/api'
import { useApi } from '@/lib/use-api'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { useFacility } from '@/features/facility/facility-context'
import type { Court,Category } from '@/features/facility/types'
import { type PriceRule,money,weekdays } from './types'
export function PricingPage(){
 const {facility}=useFacility();const rules=useApi<PriceRule[]>(`/schedules/facilities/${facility.id}/pricing`);const courts=useApi<Court[]>(`/owner/facilities/${facility.id}/courts`);const categories=useApi<Category[]>('/sport-categories')
 const [dateMode,setDateMode]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('')
 async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;setBusy(true);setError('');setMessage('');const form=e.currentTarget;const v=new FormData(form);const value=(key:string)=>String(v.get(key)||'')
  try{await api(`/schedules/facilities/${facility.id}/pricing`,{method:'POST',body:JSON.stringify({courtId:value('courtId')||null,sportCategoryId:value('sportCategoryId')||null,dayOfWeek:dateMode?null:Number(value('dayOfWeek')),specificDate:dateMode?value('specificDate'):null,startsAt:value('startsAt'),endsAt:value('endsAt'),pricePerSlot:Number(value('price')),priority:Number(value('priority')),label:value('label'),effectiveFrom:value('effectiveFrom'),effectiveTo:value('effectiveTo')||null,currency:'VND'})});rules.reload();form.reset();setMessage('Đã lưu quy tắc giá. Lịch đặt trước đó giữ nguyên giá đã chốt.')}
  catch(err){setError(err instanceof Error?err.message:'Không thể lưu bảng giá.')}finally{setBusy(false)}
 }
 async function disable(id:string){if(!window.confirm('Ngừng áp dụng quy tắc giá này cho lượt đặt mới?'))return;setBusy(true);setError('');try{await api(`/schedules/facilities/${facility.id}/pricing/${id}`,{method:'DELETE'});rules.reload()}catch(err){setError(err instanceof Error?err.message:'Không thể ngừng giá.')}finally{setBusy(false)}}
 const selectClass='rounded-lg border bg-white p-3'
 return <section className="space-y-6"><div className="flex flex-wrap justify-between gap-4"><div><h2 className="text-2xl font-bold">Bảng giá</h2><p className="mt-2 text-sm text-slate-500">Giá mỗi slot theo lịch mở cửa. Quy tắc theo sân hoặc ngày cụ thể được ưu tiên.</p></div><Link className="text-sm text-emerald-700 underline" href={`/owner/facilities/${facility.id}/schedule/preview`}>Xem trước giá</Link></div>
  <form onSubmit={save} className="grid gap-4 rounded-2xl border p-5 sm:grid-cols-2"><label className="grid gap-2 text-sm">Tên quy tắc<Input name="label" required maxLength={200} disabled={busy}/></label><label className="grid gap-2 text-sm">Sân<select className={selectClass} name="courtId" disabled={busy}><option value="">Toàn cơ sở</option>{courts.data?.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="grid gap-2 text-sm">Môn thể thao<select className={selectClass} name="sportCategoryId" disabled={busy}><option value="">Tất cả môn</option>{categories.data?.filter(c=>c.active).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>
   <label className="flex items-center gap-3 text-sm"><input type="checkbox" checked={dateMode} onChange={e=>setDateMode(e.target.checked)} disabled={busy}/>Áp dụng một ngày cụ thể</label>
   {dateMode?<label className="grid gap-2 text-sm">Ngày cụ thể<Input name="specificDate" type="date" required disabled={busy}/></label>:<label className="grid gap-2 text-sm">Ngày trong tuần<select className={selectClass} name="dayOfWeek" disabled={busy}>{weekdays.map((day,i)=><option key={day} value={i+1}>{day}</option>)}</select></label>}
   <label className="grid gap-2 text-sm">Giá mỗi slot (VNĐ)<Input name="price" type="number" min={1} max={9999999999} step={1} required disabled={busy}/></label><label className="grid gap-2 text-sm">Từ giờ<Input name="startsAt" type="time" required disabled={busy}/></label><label className="grid gap-2 text-sm">Đến giờ<Input name="endsAt" type="time" required disabled={busy}/></label><label className="grid gap-2 text-sm">Hiệu lực từ<Input name="effectiveFrom" type="date" required disabled={busy}/></label><label className="grid gap-2 text-sm">Hiệu lực đến (tùy chọn)<Input name="effectiveTo" type="date" disabled={busy}/></label><label className="grid gap-2 text-sm">Ưu tiên trong cùng cấp<Input name="priority" type="number" min={0} max={10000} defaultValue={0} required disabled={busy}/></label><Button className="self-end" disabled={busy} type="submit">{busy?'Đang lưu…':'Thêm quy tắc giá'}</Button>
  </form>{(error||rules.error||courts.error||categories.error)&&<p role="alert" className="text-red-700">{error||rules.error||courts.error||categories.error}</p>}{message&&<p role="status" className="text-emerald-700">{message}</p>}{rules.loading&&<p role="status">Đang tải bảng giá…</p>}{rules.data?.length===0&&<p className="text-slate-500">Chưa có quy tắc giá. Slot chưa có giá sẽ khóa thao tác đặt.</p>}
  <div className="space-y-3">{rules.data?.map(r=><article key={r.id} className={`flex flex-wrap items-center justify-between gap-4 rounded-xl border p-5 ${r.active?'':'opacity-60'}`}><div><h3 className="font-bold">{r.label} · {money(r.pricePerSlot)}</h3><p className="mt-2 text-sm text-slate-500">{r.courtId?courts.data?.find(c=>c.id===r.courtId)?.name:'Toàn cơ sở'} · {r.specificDate||weekdays[(r.dayOfWeek||1)-1]} · {r.startsAt}–{r.endsAt}</p><p className="mt-1 text-xs text-slate-500">{r.effectiveFrom} → {r.effectiveTo||'không giới hạn'} · Ưu tiên {r.priority} · {r.active?'Đang áp dụng':'Đã ngừng'}</p></div>{r.active&&<button disabled={busy} onClick={()=>disable(r.id)} className="text-sm text-red-700">Ngừng áp dụng</button>}</article>)}</div>
 </section>
}
