'use client'
import Link from 'next/link'
import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { api } from '@/lib/api'
import { useApi } from '@/lib/use-api'
import { RequireAuth } from '@/features/auth/require-auth'
import { Button } from '@/components/ui/button'
import { FacilityShell,useFacility } from '@/features/facility/facility-context'
import { FacilityForm } from '@/features/facility/facility-form'
import { LegalFields,legalFrom } from './apply-page'
import { applicationLabels,isEditable,type OwnerApplication,type ApplicationDetail } from './types'
export function OwnApplications(){return <RequireAuth><List/></RequireAuth>}
function List(){const r=useApi<OwnerApplication[]>('/owner-applications');return <main className="mx-auto max-w-4xl px-5 py-10"><div className="flex flex-wrap items-center justify-between gap-4"><h1 className="text-3xl font-black">Hồ sơ đăng ký Owner</h1>{(!r.data?.length||r.data.every(a=>a.state==='REJECTED'))&&<Link className="rounded-full bg-emerald-600 px-5 py-3 text-sm text-white" href="/owner/apply">Đăng ký trở thành Owner</Link>}</div>{r.loading&&<p role="status" className="mt-6">Đang tải hồ sơ…</p>}{r.error&&<Failure message={r.error} retry={r.reload}/>}<div className="mt-8 space-y-4">{r.data?.map(a=><Link key={a.id} href={`/owner/application/${a.id}`} className="block rounded-2xl border p-6 hover:border-emerald-400"><span className="text-sm font-semibold text-emerald-700">{applicationLabels[a.state]}</span><h2 className="mt-3 text-xl font-bold">{a.businessName}</h2><p className="mt-2 text-slate-500">{a.facilityName}</p>{a.reason&&<p className="mt-3 text-sm">{a.reason}</p>}</Link>)}</div>{r.data?.length===0&&<p className="mt-6 rounded-2xl border border-dashed p-6 text-slate-500">Bạn chưa có hồ sơ. Bắt đầu với thông tin pháp lý và cơ sở đầu tiên.</p>}</main>}
export function Failure({message,retry}:{message:string;retry:()=>void}){return <p role="alert" className="my-6 rounded-xl bg-red-50 p-5 text-red-700">{message}<button className="ml-3 underline" onClick={retry}>Thử lại</button></p>}
export function OwnApplication({id}:{id:string}){return <RequireAuth><Detail id={id}/></RequireAuth>}
function Detail({id}:{id:string}){
 const r=useApi<ApplicationDetail>(`/owner-applications/${id}`);const [confirm,setConfirm]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[feedback,setFeedback]=useState('')
 async function submit(){if(busy)return;setBusy(true);setError('');try{const next=await api<OwnerApplication>(`/owner-applications/${id}/submit`,{method:'POST'});setConfirm(false);setFeedback(next.state==='PENDING_APPROVAL'?'Hồ sơ đã gửi đến Admin.':'SportHub đang gửi hồ sơ. Bạn có thể tải lại để theo dõi.');r.reload()}catch(err){setError(err instanceof Error?err.message:'Không thể gửi hồ sơ.')}finally{setBusy(false)}}
 if(r.loading)return <p role="status" className="p-8">Đang tải hồ sơ…</p>;if(!r.data)return <div className="mx-auto max-w-4xl p-8"><Failure message={r.error} retry={r.reload}/></div>;const a=r.data.application
 return <main className="mx-auto max-w-4xl px-5 py-10"><Link href="/owner/application" className="text-sm text-slate-500">Hồ sơ đăng ký Owner</Link><h1 className="mt-4 text-3xl font-black">{a.businessName}</h1><section className="mt-6 rounded-2xl border p-6"><p className="font-bold text-emerald-700">{applicationLabels[a.state]}</p>{a.submittedAt&&<p className="mt-3 text-sm text-slate-500">Gửi lúc {new Date(a.submittedAt).toLocaleString('vi-VN')}</p>}{a.reason&&<p className="mt-4 whitespace-pre-wrap rounded-xl bg-amber-50 p-4 text-amber-900">{a.reason}</p>}{a.lastError&&<p role="alert" className="mt-4 text-red-700">{a.lastError}</p>}
 {isEditable(a.state)&&<><p className="mt-4 text-sm text-slate-600">Hoàn thiện ít nhất một sân đang bật, lịch mở cửa, giá, ảnh cơ sở và hai tài liệu về định danh và quyền sử dụng địa điểm. Sau khi gửi, thông tin được giữ nguyên để thẩm định.</p><div className="mt-5 flex flex-wrap gap-4 text-sm text-emerald-700"><Link className="underline" href={`/owner/application/${id}/legal`}>Thông tin pháp lý</Link><Link className="underline" href={`/owner/application/${id}/facility`}>Chuẩn bị cơ sở, sân và tài liệu</Link></div><Button className="mt-6 bg-emerald-600 text-white" onClick={()=>setConfirm(true)}>Gửi hồ sơ thẩm định</Button></>}
 {a.state==='PENDING_APPROVAL'&&<p className="mt-4 text-sm text-slate-600">Admin đang thẩm định hồ sơ. Khi được phê duyệt, phiên cũ sẽ kết thúc; đăng nhập lại để sử dụng quyền Owner.</p>}
 {['SUBMITTING','DECIDING','APPROVING'].includes(a.state)&&<p role="status" className="mt-4 text-sm text-amber-800">Đang xử lý hồ sơ. SportHub sẽ tiếp tục khi dịch vụ sẵn sàng. Khi Owner được kích hoạt, hãy đăng nhập lại.</p>}
 {a.state==='APPROVED'&&<div className="mt-5"><p className="text-sm">Hồ sơ đã được phê duyệt. Phí nền tảng: {a.commissionPercent}%.</p><Link className="mt-4 inline-block rounded-full bg-emerald-600 px-5 py-3 text-white" href={`/owner/facilities/${a.facilityId}`}>Quản lý cơ sở</Link></div>}
 {a.state==='REJECTED'&&<Link href="/owner/apply" className="mt-5 inline-block text-emerald-700 underline">Tạo hồ sơ đăng ký mới</Link>}<Button className="ml-3 mt-5" variant="outline" onClick={r.reload} disabled={busy}>Cập nhật trạng thái</Button></section>
 {confirm&&<section role="dialog" aria-label="Xác nhận gửi hồ sơ Owner" className="mt-6 rounded-2xl border bg-emerald-50 p-6"><h2 className="text-xl font-bold">Gửi hồ sơ để Admin thẩm định?</h2><p className="mt-3 text-sm">Thông tin pháp lý, tài liệu và cấu hình cơ sở hiện tại sẽ được lưu thành hồ sơ thẩm định.</p><div className="mt-5 flex gap-3"><Button onClick={submit} disabled={busy}>{busy?'Đang gửi…':'Xác nhận gửi hồ sơ'}</Button><Button variant="outline" onClick={()=>setConfirm(false)} disabled={busy}>Tiếp tục chỉnh sửa</Button></div></section>}{error&&<p role="alert" className="mt-4 text-red-700">{error}</p>}{feedback&&<p role="status" className="mt-4 text-emerald-700">{feedback}</p>}
 <section className="mt-8 rounded-2xl border p-6"><h2 className="text-xl font-bold">Cơ sở đầu tiên</h2><p className="mt-3">{r.data.facility.facility.name} · {r.data.facility.courts.length} sân</p><p className="mt-2 text-sm text-slate-500">{r.data.facility.facility.addressLine}, {r.data.facility.facility.district}, {r.data.facility.facility.province}</p><Link href={`/owner/application/${id}/facility`} className="mt-4 inline-block text-sm text-emerald-700 underline">Xem hồ sơ cơ sở</Link></section>
 <section className="mt-8"><h2 className="text-xl font-bold">Lịch sử gửi hồ sơ</h2>{r.data.history.length===0&&<p className="mt-3 text-sm text-slate-500">Chưa gửi thẩm định.</p>}{r.data.history.map((h,i)=><p className="mt-3 rounded-xl bg-slate-50 p-4 text-sm" key={h.id}>Lần {r.data!.history.length-i} · {new Date(h.submittedAt).toLocaleString('vi-VN')}</p>)}</section></main>
}
export function ApplicationLegalPage({id}:{id:string}){return <RequireAuth><LegalEditor id={id}/></RequireAuth>}
function LegalEditor({id}:{id:string}){const r=useApi<ApplicationDetail>(`/owner-applications/${id}`),router=useRouter();const [busy,setBusy]=useState(false),[error,setError]=useState('');async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;setBusy(true);setError('');try{await api(`/owner-applications/${id}/legal`,{method:'PUT',body:JSON.stringify(legalFrom(new FormData(e.currentTarget)))});router.push(`/owner/application/${id}`)}catch(err){setError(err instanceof Error?err.message:'Không thể lưu thông tin.')}finally{setBusy(false)}}return <main className="mx-auto max-w-4xl px-5 py-10"><Link href={`/owner/application/${id}`} className="text-sm text-emerald-700 underline">Quay lại hồ sơ</Link><h1 className="mt-5 text-3xl font-bold">Thông tin pháp lý</h1>{r.loading&&<p role="status" className="mt-6">Đang tải…</p>}{r.error&&<Failure message={r.error} retry={r.reload}/>} {r.data&&<form onSubmit={save} className="mt-8"><fieldset disabled={!isEditable(r.data.application.state)||busy} className="grid gap-5 rounded-2xl border p-6 md:grid-cols-2"><LegalFields legal={r.data.legal} busy={busy}/><Button type="submit" className="bg-emerald-600 text-white">{busy?'Đang lưu…':'Lưu thông tin pháp lý'}</Button></fieldset>{!isEditable(r.data.application.state)&&<p className="mt-4 text-sm text-amber-800">Thông tin được giữ nguyên trong thời gian thẩm định.</p>}</form>}{error&&<p role="alert" className="mt-5 text-red-700">{error}</p>}</main>}
export function ApplicationWorkspace({id,children}:{id:string;children:React.ReactNode}){return <RequireAuth><Workspace id={id}>{children}</Workspace></RequireAuth>}
function Workspace({id,children}:{id:string;children:React.ReactNode}){const r=useApi<ApplicationDetail>(`/owner-applications/${id}`);if(r.loading)return <p role="status" className="p-8">Đang tải cơ sở đăng ký…</p>;if(!r.data)return <div className="p-8"><Failure message={r.error} retry={r.reload}/></div>;return <FacilityShell id={r.data.application.facilityId} applicationId={id}>{children}</FacilityShell>}
export function ApplicationFacilityEditor(){const {facility,reload,basePath}=useFacility();return <FacilityForm facility={facility} onSaved={reload} redirectPath={basePath}/>}
